[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/categories"
  to = "/.netlify/functions/categories"
  status = 200

[[redirects]]
  from = "/api/questions"
  to = "/.netlify/functions/questions"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 